# Reddit Persona Validator Configuration

# Core configuration
core:
  # Timeouts in seconds
  timeouts:
    request: 30
    browser: 45
    email: 60
  
  # User agent for requests
  user_agent: "RedditPersonaValidator/1.0.0"
  
  # Retry configuration
  retries:
    max_attempts: 3
    backoff_factor: 2
    retry_statuses: [429, 500, 502, 503, 504]

# Proxy configuration
proxy:
  enabled: false
  use_rotation: true
  check_health: true
  timeout: 10
  sources:
    - type: file
      path: config/proxies.txt
    - type: api
      url: ""
      key: ""
      refresh_interval: 3600

# Browser configuration
browser:
  headless: true
  timeout: 60
  use_stealth: true
  user_data_dir: "data/browser_profiles"

# Email verification
email:
  enabled: true
  protocols:
    - imap
  servers:
    hotmail:
      host: "outlook.office365.com"
      port: 993
      ssl: true

# Reddit API configuration
reddit:
  client_id: ""
  client_secret: ""
  redirect_uri: "http://localhost:8000/reddit/callback"
  user_agent: "RedditPersonaValidator/1.0.0"
  scopes: ["identity", "read"]

# AI analysis configuration
analysis:
  default_engine: "claude"  # Options: claude, deepseek, mock
  cache_results: true
  cache_ttl: 86400  # 24 hours in seconds
  
  # Claude configuration
  claude:
    api_key: ""
    model: "claude-3-opus-20240229"
    temperature: 0.1
    max_tokens: 4000
  
  # DeepSeek configuration
  deepseek:
    api_key: ""
    api_base: "https://api.deepseek.com/v1"
    model: "deepseek-chat"
    temperature: 0.1
    max_tokens: 4000
  
  # Scoring weights (0-1)
  scoring:
    account_age_weight: 0.2
    karma_weight: 0.15
    email_verification_weight: 0.3
    content_analysis_weight: 0.35
    
    # Thresholds
    min_account_age_days: 30
    min_karma: 100
    suspicious_score_threshold: 40
    trusted_score_threshold: 75

# Interface configuration
interface:
  # CLI configuration
  cli:
    enable_colors: true
    progress_bar: true
    output_format: "text"  # Options: text, json, csv
  
  # API configuration
  api:
    host: "0.0.0.0"
    port: 8000
    log_level: "info"
    cors_origins: ["*"]
    api_keys: []  # List of valid API keys
  
  # GUI configuration
  gui:
    theme: "DarkAmber"
    save_window_position: true
    auto_update: true

# Database configuration
database:
  engine: "sqlite"
  path: "data/validator.db"
  cache_expiry: 86400  # 24 hours in seconds
  pool_size: 5
  enable_query_logging: false
  
  # Redis configuration (for distributed deployments)
  redis:
    enabled: false
    host: "redis"
    port: 6379
    db: 0
    password: ""
    prefix: "rpv:"

# Visualization configuration
visualization:
  # Dashboard configuration
  dashboard:
    host: "0.0.0.0"
    port: 8050
    debug: false
    theme: "darkly"
    refresh_interval: 60  # In seconds
    
    # Chart defaults
    chart_defaults:
      height: 400
      margin: {"l": 40, "r": 40, "t": 10, "b": 40}
      template: "plotly_dark"
    
    # Data export options
    exports:
      enable_csv: true
      enable_excel: true
      enable_pdf: true
