# Configuration for Reddit Persona Validator

# Reddit API settings
reddit:
  user_agent: "RedditPersonaValidator/0.1.0"
  request_timeout: 30
  captcha_timeout: 45

# Email verification settings
email:
  imap_server: "outlook.office365.com"
  imap_port: 993
  connection_timeout: 30
  verification_timeout: 300

# AI Analysis settings
ai:
  # General AI settings
  enabled: true
  default_analyzer: "deepseek"  # Options: deepseek, claude, mock
  fallback_analyzer: "mock"     # Fallback analyzer if primary fails
  cache_results: true           # Cache analysis results to avoid redundant API calls
  cache_expiry: 86400           # Cache expiry in seconds (24 hours)
  
  # DeepSeek settings
  deepseek:
    api_key: ""  # Set in .env file
    api_url: "https://api.deepseek.com/v1/chat/completions"
    api_timeout: 60
    model: "deepseek-chat"
    temperature: 0.2
    max_tokens: 1024
    batch_size: 5       # Number of accounts to analyze in a single API call
    rate_limit: 100     # API calls per minute
    retry_attempts: 3   # Number of retry attempts
    retry_delay: 2      # Delay between retries in seconds
  
  # Claude settings
  claude:
    api_key: ""  # Set in .env file
    api_url: "https://api.anthropic.com/v1/complete"
    api_timeout: 60
    model: "claude-3-sonnet-20240229"
    temperature: 0.1
    max_tokens: 1024
    batch_size: 3       # Number of accounts to analyze in a single API call
    rate_limit: 50      # API calls per minute
    retry_attempts: 3   # Number of retry attempts
    retry_delay: 2      # Delay between retries in seconds
  
  # Analysis weights
  weights:
    content_coherence: 0.25     # Weight for content coherence score
    language_quality: 0.20      # Weight for language quality score
    account_consistency: 0.25   # Weight for account activity consistency
    behavioral_patterns: 0.30   # Weight for behavioral patterns score

# Proxy settings
proxy:
  rotation_interval: 300
  health_check_interval: 60
  max_failures: 3
  connection_timeout: 10

# Scoring thresholds
scoring:
  min_account_age_days: 30
  min_karma: 100
  email_verification_weight: 0.3
  account_age_weight: 0.2
  karma_weight: 0.2
  ai_analysis_weight: 0.3       # Weight for AI analysis in trust score
  trust_threshold: 0.7

# Interface settings
interface:
  cli:
    log_level: "INFO"
    progress_bar: true
    ai_analysis_detail_level: "medium"  # Options: none, basic, medium, full
  gui:
    theme: "DarkGrey9"
    window_size: [800, 600]
    show_ai_analysis: true
    ai_tab_enabled: true
  api:
    host: "0.0.0.0"
    port: 8000
    log_level: "INFO"
    cors_origins: ["*"]
    rate_limit:
      enabled: true
      requests_per_minute: 60
    ai_analysis:
      endpoint_enabled: true
      async_processing: true

# Analysis settings
analysis:
  default_analyzer: "deepseek"  # deepseek|claude|mock
  mock_mode: False
  cache_enabled: True
  cache_dir: ".cache/analysis"
  content_samples: 10           # Number of content samples to analyze
  user_behavior_metrics: [
    "posting_frequency",
    "comment_engagement",
    "subreddit_diversity",
    "content_consistency"
  ]
  sensitive_content_detection: true
  batch_processing:
    enabled: true
    max_batch_size: 10
    concurrent_jobs: 2
