name: Deploy to AWS

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Extract tag name
      id: tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./infrastructure/Dockerfile
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/reddit-persona-validator:${{ steps.tag.outputs.VERSION }}
          ${{ steps.login-ecr.outputs.registry }}/reddit-persona-validator:latest
    
    - name: Deploy to AWS Lightsail
      run: |
        aws lightsail create-container-service-deployment \
          --service-name reddit-persona-validator \
          --containers '{"app":{"image":"${{ steps.login-ecr.outputs.registry }}/reddit-persona-validator:${{ steps.tag.outputs.VERSION }}","ports":{"8000":"HTTP"}}}' \
          --public-endpoint '{"containerName":"app","containerPort":8000,"healthCheck":{"path":"/health"}}'
